# .github/workflows/preview.yml
name: Deploy PR previews

# 
concurrency: preview-${{ github.ref }} 

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          pages-base-url: linuxupc.org
          comment: true
          action: auto